import { Resource } from '../stores/resourceStore';

export const mockResources: Resource[] = [
  {
    id: '1',
    name: 'Alice Chen',
    role: 'Software Engineer',
    projectId: 'p1',
    projectName: 'Digital Transformation',
    chargeability: 100,
    startDate: '2024-01-15',
    endDate: '2024-06-30',
    skillset: ['React', 'Node.js', 'TypeScript'],
    status: 'assigned',
    seatLocation: 's1',
  },
  {
    id: '2',
    name: 'Bob Williams',
    role: 'UX Designer',
    projectId: 'p1',
    projectName: 'Digital Transformation',
    chargeability: 80,
    startDate: '2024-02-01',
    endDate: null,
    skillset: ['Figma', 'UI/UX Research', 'Prototyping'],
    status: 'assigned',
    seatLocation: 's2',
  },
  {
    id: '3',
    name: 'Carol Martinez',
    role: 'Business Analyst',
    projectId: 'p2',
    projectName: 'ERP Implementation',
    chargeability: 100,
    startDate: '2024-03-10',
    endDate: '2024-08-15',
    skillset: ['Requirements Analysis', 'SQL', 'Process Modeling'],
    status: 'assigned',
    seatLocation: 's3',
  },
  {
    id: '4',
    name: 'Dave Johnson',
    role: 'DevOps Engineer',
    projectId: null,
    projectName: null,
    chargeability: 0,
    startDate: null,
    endDate: null,
    skillset: ['Docker', 'Kubernetes', 'CI/CD', 'AWS'],
    status: 'available',
    seatLocation: 's4',
  },
  {
    id: '5',
    name: 'Eva Brown',
    role: 'Project Manager',
    projectId: 'p3',
    projectName: 'Cloud Migration',
    chargeability: 50,
    startDate: '2024-01-05',
    endDate: '2024-12-31',
    skillset: ['Agile', 'Scrum', 'Risk Management'],
    status: 'partially_available',
    seatLocation: 's5',
  },
];